// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: users.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/freifunkMUC/wg-access-server/proto/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UsersName is the fully-qualified name of the Users service.
	UsersName = "proto.Users"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UsersListUsersProcedure is the fully-qualified name of the Users's ListUsers RPC.
	UsersListUsersProcedure = "/proto.Users/ListUsers"
	// UsersDeleteUserProcedure is the fully-qualified name of the Users's DeleteUser RPC.
	UsersDeleteUserProcedure = "/proto.Users/DeleteUser"
)

// UsersClient is a client for the proto.Users service.
type UsersClient interface {
	// admin only
	ListUsers(context.Context, *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error)
	DeleteUser(context.Context, *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error)
}

// NewUsersClient constructs a client for the proto.Users service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUsersClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UsersClient {
	baseURL = strings.TrimRight(baseURL, "/")
	usersMethods := proto.File_users_proto.Services().ByName("Users").Methods()
	return &usersClient{
		listUsers: connect.NewClient[proto.ListUsersReq, proto.ListUsersRes](
			httpClient,
			baseURL+UsersListUsersProcedure,
			connect.WithSchema(usersMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[proto.DeleteUserReq, emptypb.Empty](
			httpClient,
			baseURL+UsersDeleteUserProcedure,
			connect.WithSchema(usersMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// usersClient implements UsersClient.
type usersClient struct {
	listUsers  *connect.Client[proto.ListUsersReq, proto.ListUsersRes]
	deleteUser *connect.Client[proto.DeleteUserReq, emptypb.Empty]
}

// ListUsers calls proto.Users.ListUsers.
func (c *usersClient) ListUsers(ctx context.Context, req *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// DeleteUser calls proto.Users.DeleteUser.
func (c *usersClient) DeleteUser(ctx context.Context, req *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// UsersHandler is an implementation of the proto.Users service.
type UsersHandler interface {
	// admin only
	ListUsers(context.Context, *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error)
	DeleteUser(context.Context, *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error)
}

// NewUsersHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUsersHandler(svc UsersHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	usersMethods := proto.File_users_proto.Services().ByName("Users").Methods()
	usersListUsersHandler := connect.NewUnaryHandler(
		UsersListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(usersMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	usersDeleteUserHandler := connect.NewUnaryHandler(
		UsersDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(usersMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.Users/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UsersListUsersProcedure:
			usersListUsersHandler.ServeHTTP(w, r)
		case UsersDeleteUserProcedure:
			usersDeleteUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUsersHandler returns CodeUnimplemented from all methods.
type UnimplementedUsersHandler struct{}

func (UnimplementedUsersHandler) ListUsers(context.Context, *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.ListUsers is not implemented"))
}

func (UnimplementedUsersHandler) DeleteUser(context.Context, *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.DeleteUser is not implemented"))
}
