// Generated by protoc-gen-grpc-ts-web. DO NOT EDIT!
/* eslint-disable */
/* tslint:disable */

import * as jspb from 'google-protobuf';
import * as grpcWeb from 'grpc-web';

// grpc-web >= 2 types a MethodDescriptor's message classes as
// new (...args: unknown[]) => T, while the classes emitted by protoc-gen-js
// take an optional jspb.Message.MessageArray. The two are not assignable under
// strictFunctionTypes, so the constructors are bridged through this alias.
// It changes types only - the values handed to grpc-web are unchanged.
type MessageCtor<T> = new (...args: unknown[]) => T;

import * as googleProtobufEmpty from 'google-protobuf/google/protobuf/empty_pb';
import * as googleProtobufTimestamp from 'google-protobuf/google/protobuf/timestamp_pb';

export class Users {

	private client_ = new grpcWeb.GrpcWebClientBase({
		format: 'binary',
	});

	private methodInfoListUsers = new grpcWeb.MethodDescriptor<ListUsersReq, ListUsersRes>(
		"ListUsers",
		'unary',
		ListUsersReq as unknown as MessageCtor<ListUsersReq>,
		ListUsersRes as unknown as MessageCtor<ListUsersRes>,
		(req: ListUsersReq) => req.serializeBinary(),
		ListUsersRes.deserializeBinary
	);

	private methodInfoDeleteUser = new grpcWeb.MethodDescriptor<DeleteUserReq, googleProtobufEmpty.Empty>(
		"DeleteUser",
		'unary',
		DeleteUserReq as unknown as MessageCtor<DeleteUserReq>,
		googleProtobufEmpty.Empty as unknown as MessageCtor<googleProtobufEmpty.Empty>,
		(req: DeleteUserReq) => req.serializeBinary(),
		googleProtobufEmpty.Empty.deserializeBinary
	);

	private methodInfoRevokeAccess = new grpcWeb.MethodDescriptor<RevokeAccessReq, RevokeAccessRes>(
		"RevokeAccess",
		'unary',
		RevokeAccessReq as unknown as MessageCtor<RevokeAccessReq>,
		RevokeAccessRes as unknown as MessageCtor<RevokeAccessRes>,
		(req: RevokeAccessReq) => req.serializeBinary(),
		RevokeAccessRes.deserializeBinary
	);

	private methodInfoChangePassword = new grpcWeb.MethodDescriptor<ChangePasswordReq, ChangePasswordRes>(
		"ChangePassword",
		'unary',
		ChangePasswordReq as unknown as MessageCtor<ChangePasswordReq>,
		ChangePasswordRes as unknown as MessageCtor<ChangePasswordRes>,
		(req: ChangePasswordReq) => req.serializeBinary(),
		ChangePasswordRes.deserializeBinary
	);

	private methodInfoStartTwoFactor = new grpcWeb.MethodDescriptor<StartTwoFactorReq, StartTwoFactorRes>(
		"StartTwoFactor",
		'unary',
		StartTwoFactorReq as unknown as MessageCtor<StartTwoFactorReq>,
		StartTwoFactorRes as unknown as MessageCtor<StartTwoFactorRes>,
		(req: StartTwoFactorReq) => req.serializeBinary(),
		StartTwoFactorRes.deserializeBinary
	);

	private methodInfoConfirmTwoFactor = new grpcWeb.MethodDescriptor<ConfirmTwoFactorReq, ConfirmTwoFactorRes>(
		"ConfirmTwoFactor",
		'unary',
		ConfirmTwoFactorReq as unknown as MessageCtor<ConfirmTwoFactorReq>,
		ConfirmTwoFactorRes as unknown as MessageCtor<ConfirmTwoFactorRes>,
		(req: ConfirmTwoFactorReq) => req.serializeBinary(),
		ConfirmTwoFactorRes.deserializeBinary
	);

	private methodInfoDisableTwoFactor = new grpcWeb.MethodDescriptor<DisableTwoFactorReq, googleProtobufEmpty.Empty>(
		"DisableTwoFactor",
		'unary',
		DisableTwoFactorReq as unknown as MessageCtor<DisableTwoFactorReq>,
		googleProtobufEmpty.Empty as unknown as MessageCtor<googleProtobufEmpty.Empty>,
		(req: DisableTwoFactorReq) => req.serializeBinary(),
		googleProtobufEmpty.Empty.deserializeBinary
	);

	private methodInfoResetTwoFactor = new grpcWeb.MethodDescriptor<ResetTwoFactorReq, googleProtobufEmpty.Empty>(
		"ResetTwoFactor",
		'unary',
		ResetTwoFactorReq as unknown as MessageCtor<ResetTwoFactorReq>,
		googleProtobufEmpty.Empty as unknown as MessageCtor<googleProtobufEmpty.Empty>,
		(req: ResetTwoFactorReq) => req.serializeBinary(),
		googleProtobufEmpty.Empty.deserializeBinary
	);

	constructor(
		private hostname: string,
		private defaultMetadata?: () => grpcWeb.Metadata,
	) { }

	listUsers(req: ListUsersReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ListUsersRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ListUsersReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/ListUsers',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoListUsers,
				(err: grpcWeb.Error, res: ListUsersRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	deleteUser(req: DeleteUserReq.AsObject, metadata?: grpcWeb.Metadata): Promise<googleProtobufEmpty.Empty.AsObject> {
		return new Promise((resolve, reject) => {
			const message = DeleteUserReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/DeleteUser',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoDeleteUser,
				(err: grpcWeb.Error, res: googleProtobufEmpty.Empty) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	revokeAccess(req: RevokeAccessReq.AsObject, metadata?: grpcWeb.Metadata): Promise<RevokeAccessRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = RevokeAccessReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/RevokeAccess',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoRevokeAccess,
				(err: grpcWeb.Error, res: RevokeAccessRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	changePassword(req: ChangePasswordReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ChangePasswordRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ChangePasswordReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/ChangePassword',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoChangePassword,
				(err: grpcWeb.Error, res: ChangePasswordRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	startTwoFactor(req: StartTwoFactorReq.AsObject, metadata?: grpcWeb.Metadata): Promise<StartTwoFactorRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = StartTwoFactorReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/StartTwoFactor',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoStartTwoFactor,
				(err: grpcWeb.Error, res: StartTwoFactorRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	confirmTwoFactor(req: ConfirmTwoFactorReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ConfirmTwoFactorRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ConfirmTwoFactorReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/ConfirmTwoFactor',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoConfirmTwoFactor,
				(err: grpcWeb.Error, res: ConfirmTwoFactorRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	disableTwoFactor(req: DisableTwoFactorReq.AsObject, metadata?: grpcWeb.Metadata): Promise<googleProtobufEmpty.Empty.AsObject> {
		return new Promise((resolve, reject) => {
			const message = DisableTwoFactorReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/DisableTwoFactor',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoDisableTwoFactor,
				(err: grpcWeb.Error, res: googleProtobufEmpty.Empty) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	resetTwoFactor(req: ResetTwoFactorReq.AsObject, metadata?: grpcWeb.Metadata): Promise<googleProtobufEmpty.Empty.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ResetTwoFactorReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Users/ResetTwoFactor',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoResetTwoFactor,
				(err: grpcWeb.Error, res: googleProtobufEmpty.Empty) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

}




export declare namespace User {
	export type AsObject = {
		name: string,
		displayName: string,
		lastLogin?: googleProtobufTimestamp.Timestamp.AsObject,
		policies: Array<string>,
		twoFactor: boolean,
	}
}

export class User extends jspb.Message {

	private static repeatedFields_ = [
		4,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, User.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getDisplayName(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setDisplayName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getLastLogin(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 3);
	}

	setLastLogin(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 3, value);
	}

	getPolicies(): Array<string> {return jspb.Message.getFieldWithDefault(this, 4, [""]);
	}

	setPolicies(value: Array<string>): void {
		(jspb.Message as any).setProto3StringField(this, 4, value);
	}

	addPolicies(value: string, index?: number): void {
		return jspb.Message.addToRepeatedField(this, 4, value, index);
	}

	getTwoFactor(): boolean {return jspb.Message.getFieldWithDefault(this, 5, false);
	}

	setTwoFactor(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 5, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		User.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): User.AsObject {
		let f: any;
		return {
			name: this.getName(),
			displayName: this.getDisplayName(),
			lastLogin: (f = this.getLastLogin()) && f.toObject(),
			policies: this.getPolicies(),
			twoFactor: this.getTwoFactor(),
		};
	}

	static serializeBinaryToWriter(message: User, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getDisplayName();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getLastLogin();
		if (field3 != null) {
			writer.writeMessage(3, field3, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field4 = message.getPolicies();
		if (field4.length > 0) {
			writer.writeRepeatedString(4, field4);
		}
		const field5 = message.getTwoFactor();
		if (field5 != false) {
			writer.writeBool(5, field5);
		}
	}

	static deserializeBinary(bytes: Uint8Array): User {
		var reader = new jspb.BinaryReader(bytes);
		var message = new User();
		return User.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: User, reader: jspb.BinaryReader): User {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setDisplayName(field2);
				break;
			case 3:
				const field3 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field3, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setLastLogin(field3);
				break;
			case 4:
				const field4 = reader.readString()
				message.addPolicies(field4);
				break;
			case 5:
				const field5 = reader.readBool()
				message.setTwoFactor(field5);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListUsersReq {
	export type AsObject = {
	}
}

export class ListUsersReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListUsersReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListUsersReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListUsersReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: ListUsersReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): ListUsersReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListUsersReq();
		return ListUsersReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListUsersReq, reader: jspb.BinaryReader): ListUsersReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListUsersRes {
	export type AsObject = {
		items: Array<User.AsObject>,
	}
}

export class ListUsersRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListUsersRes.repeatedFields_, null);
	}


	getItems(): Array<User> {
		return jspb.Message.getRepeatedWrapperField(this, User, 1);
	}

	setItems(value: Array<User>): void {
		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
	}

	addItems(value?: User, index?: number): User {
		return jspb.Message.addToRepeatedWrapperField(this, 1, value, User, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListUsersRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListUsersRes.AsObject {
		let f: any;
		return {
			items: this.getItems().map((item) => item.toObject()),
		};
	}

	static serializeBinaryToWriter(message: ListUsersRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getItems();
		if (field1.length > 0) {
			writer.writeRepeatedMessage(1, field1, User.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ListUsersRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListUsersRes();
		return ListUsersRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListUsersRes, reader: jspb.BinaryReader): ListUsersRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new User();
				reader.readMessage(field1, User.deserializeBinaryFromReader);
				message.addItems(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DeleteUserReq {
	export type AsObject = {
		name: string,
	}
}

export class DeleteUserReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DeleteUserReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DeleteUserReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DeleteUserReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
		};
	}

	static serializeBinaryToWriter(message: DeleteUserReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): DeleteUserReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DeleteUserReq();
		return DeleteUserReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DeleteUserReq, reader: jspb.BinaryReader): DeleteUserReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ChangePasswordReq {
	export type AsObject = {
		currentPassword: string,
		newPassword: string,
	}
}

export class ChangePasswordReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ChangePasswordReq.repeatedFields_, null);
	}


	getCurrentPassword(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setCurrentPassword(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getNewPassword(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setNewPassword(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ChangePasswordReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ChangePasswordReq.AsObject {
		let f: any;
		return {
			currentPassword: this.getCurrentPassword(),
			newPassword: this.getNewPassword(),
		};
	}

	static serializeBinaryToWriter(message: ChangePasswordReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getCurrentPassword();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getNewPassword();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ChangePasswordReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ChangePasswordReq();
		return ChangePasswordReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ChangePasswordReq, reader: jspb.BinaryReader): ChangePasswordReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setCurrentPassword(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setNewPassword(field2);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ChangePasswordRes {
	export type AsObject = {
		sessionsEnded: number,
	}
}

export class ChangePasswordRes extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ChangePasswordRes.repeatedFields_, null);
	}


	getSessionsEnded(): number {return jspb.Message.getFieldWithDefault(this, 1, 0);
	}

	setSessionsEnded(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ChangePasswordRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ChangePasswordRes.AsObject {
		let f: any;
		return {
			sessionsEnded: this.getSessionsEnded(),
		};
	}

	static serializeBinaryToWriter(message: ChangePasswordRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getSessionsEnded();
		if (field1 != 0) {
			writer.writeInt32(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ChangePasswordRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ChangePasswordRes();
		return ChangePasswordRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ChangePasswordRes, reader: jspb.BinaryReader): ChangePasswordRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readInt32()
				message.setSessionsEnded(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace StartTwoFactorReq {
	export type AsObject = {
	}
}

export class StartTwoFactorReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, StartTwoFactorReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		StartTwoFactorReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): StartTwoFactorReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: StartTwoFactorReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): StartTwoFactorReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new StartTwoFactorReq();
		return StartTwoFactorReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: StartTwoFactorReq, reader: jspb.BinaryReader): StartTwoFactorReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace StartTwoFactorRes {
	export type AsObject = {
		secret: string,
		uri: string,
	}
}

export class StartTwoFactorRes extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, StartTwoFactorRes.repeatedFields_, null);
	}


	getSecret(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setSecret(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getUri(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setUri(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		StartTwoFactorRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): StartTwoFactorRes.AsObject {
		let f: any;
		return {
			secret: this.getSecret(),
			uri: this.getUri(),
		};
	}

	static serializeBinaryToWriter(message: StartTwoFactorRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getSecret();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getUri();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
	}

	static deserializeBinary(bytes: Uint8Array): StartTwoFactorRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new StartTwoFactorRes();
		return StartTwoFactorRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: StartTwoFactorRes, reader: jspb.BinaryReader): StartTwoFactorRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setSecret(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setUri(field2);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ConfirmTwoFactorReq {
	export type AsObject = {
		code: string,
	}
}

export class ConfirmTwoFactorReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ConfirmTwoFactorReq.repeatedFields_, null);
	}


	getCode(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setCode(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ConfirmTwoFactorReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ConfirmTwoFactorReq.AsObject {
		let f: any;
		return {
			code: this.getCode(),
		};
	}

	static serializeBinaryToWriter(message: ConfirmTwoFactorReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getCode();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ConfirmTwoFactorReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ConfirmTwoFactorReq();
		return ConfirmTwoFactorReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ConfirmTwoFactorReq, reader: jspb.BinaryReader): ConfirmTwoFactorReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setCode(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ConfirmTwoFactorRes {
	export type AsObject = {
		recoveryCodes: Array<string>,
	}
}

export class ConfirmTwoFactorRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ConfirmTwoFactorRes.repeatedFields_, null);
	}


	getRecoveryCodes(): Array<string> {return jspb.Message.getFieldWithDefault(this, 1, [""]);
	}

	setRecoveryCodes(value: Array<string>): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	addRecoveryCodes(value: string, index?: number): void {
		return jspb.Message.addToRepeatedField(this, 1, value, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ConfirmTwoFactorRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ConfirmTwoFactorRes.AsObject {
		let f: any;
		return {
			recoveryCodes: this.getRecoveryCodes(),
		};
	}

	static serializeBinaryToWriter(message: ConfirmTwoFactorRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getRecoveryCodes();
		if (field1.length > 0) {
			writer.writeRepeatedString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ConfirmTwoFactorRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ConfirmTwoFactorRes();
		return ConfirmTwoFactorRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ConfirmTwoFactorRes, reader: jspb.BinaryReader): ConfirmTwoFactorRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.addRecoveryCodes(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DisableTwoFactorReq {
	export type AsObject = {
		password: string,
	}
}

export class DisableTwoFactorReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DisableTwoFactorReq.repeatedFields_, null);
	}


	getPassword(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setPassword(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DisableTwoFactorReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DisableTwoFactorReq.AsObject {
		let f: any;
		return {
			password: this.getPassword(),
		};
	}

	static serializeBinaryToWriter(message: DisableTwoFactorReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getPassword();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): DisableTwoFactorReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DisableTwoFactorReq();
		return DisableTwoFactorReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DisableTwoFactorReq, reader: jspb.BinaryReader): DisableTwoFactorReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setPassword(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ResetTwoFactorReq {
	export type AsObject = {
		name: string,
	}
}

export class ResetTwoFactorReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ResetTwoFactorReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ResetTwoFactorReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ResetTwoFactorReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
		};
	}

	static serializeBinaryToWriter(message: ResetTwoFactorReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ResetTwoFactorReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ResetTwoFactorReq();
		return ResetTwoFactorReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ResetTwoFactorReq, reader: jspb.BinaryReader): ResetTwoFactorReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace RevokeAccessReq {
	export type AsObject = {
		name: string,
	}
}

export class RevokeAccessReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, RevokeAccessReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		RevokeAccessReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): RevokeAccessReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
		};
	}

	static serializeBinaryToWriter(message: RevokeAccessReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): RevokeAccessReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new RevokeAccessReq();
		return RevokeAccessReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: RevokeAccessReq, reader: jspb.BinaryReader): RevokeAccessReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace RevokeAccessRes {
	export type AsObject = {
		devicesBlocked: number,
		tokensDeleted: number,
		sessionsEnded: number,
	}
}

export class RevokeAccessRes extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, RevokeAccessRes.repeatedFields_, null);
	}


	getDevicesBlocked(): number {return jspb.Message.getFieldWithDefault(this, 1, 0);
	}

	setDevicesBlocked(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 1, value);
	}

	getTokensDeleted(): number {return jspb.Message.getFieldWithDefault(this, 2, 0);
	}

	setTokensDeleted(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 2, value);
	}

	getSessionsEnded(): number {return jspb.Message.getFieldWithDefault(this, 3, 0);
	}

	setSessionsEnded(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 3, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		RevokeAccessRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): RevokeAccessRes.AsObject {
		let f: any;
		return {
			devicesBlocked: this.getDevicesBlocked(),
			tokensDeleted: this.getTokensDeleted(),
			sessionsEnded: this.getSessionsEnded(),
		};
	}

	static serializeBinaryToWriter(message: RevokeAccessRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getDevicesBlocked();
		if (field1 != 0) {
			writer.writeInt32(1, field1);
		}
		const field2 = message.getTokensDeleted();
		if (field2 != 0) {
			writer.writeInt32(2, field2);
		}
		const field3 = message.getSessionsEnded();
		if (field3 != 0) {
			writer.writeInt32(3, field3);
		}
	}

	static deserializeBinary(bytes: Uint8Array): RevokeAccessRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new RevokeAccessRes();
		return RevokeAccessRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: RevokeAccessRes, reader: jspb.BinaryReader): RevokeAccessRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readInt32()
				message.setDevicesBlocked(field1);
				break;
			case 2:
				const field2 = reader.readInt32()
				message.setTokensDeleted(field2);
				break;
			case 3:
				const field3 = reader.readInt32()
				message.setSessionsEnded(field3);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}


function UserFromObject(obj: User.AsObject | undefined): User | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new User();
	message.setName(obj.name);
	message.setDisplayName(obj.displayName);
	message.setLastLogin(TimestampFromObject(obj.lastLogin));
	(obj.policies || [])
		.forEach((item) => message.addPolicies(item));
	message.setTwoFactor(obj.twoFactor);
	return message;
}

function TimestampFromObject(obj: googleProtobufTimestamp.Timestamp.AsObject | undefined): googleProtobufTimestamp.Timestamp | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufTimestamp.Timestamp();
	message.setSeconds(obj.seconds);
	message.setNanos(obj.nanos);
	return message;
}

function ListUsersReqFromObject(obj: ListUsersReq.AsObject | undefined): ListUsersReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListUsersReq();
	return message;
}

function ListUsersResFromObject(obj: ListUsersRes.AsObject | undefined): ListUsersRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListUsersRes();
	(obj.items || [])
		.map((item) => UserFromObject(item))
		.forEach((item) => message.addItems(item));
	return message;
}

function DeleteUserReqFromObject(obj: DeleteUserReq.AsObject | undefined): DeleteUserReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DeleteUserReq();
	message.setName(obj.name);
	return message;
}

function ChangePasswordReqFromObject(obj: ChangePasswordReq.AsObject | undefined): ChangePasswordReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ChangePasswordReq();
	message.setCurrentPassword(obj.currentPassword);
	message.setNewPassword(obj.newPassword);
	return message;
}

function ChangePasswordResFromObject(obj: ChangePasswordRes.AsObject | undefined): ChangePasswordRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ChangePasswordRes();
	message.setSessionsEnded(obj.sessionsEnded);
	return message;
}

function StartTwoFactorReqFromObject(obj: StartTwoFactorReq.AsObject | undefined): StartTwoFactorReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new StartTwoFactorReq();
	return message;
}

function StartTwoFactorResFromObject(obj: StartTwoFactorRes.AsObject | undefined): StartTwoFactorRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new StartTwoFactorRes();
	message.setSecret(obj.secret);
	message.setUri(obj.uri);
	return message;
}

function ConfirmTwoFactorReqFromObject(obj: ConfirmTwoFactorReq.AsObject | undefined): ConfirmTwoFactorReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ConfirmTwoFactorReq();
	message.setCode(obj.code);
	return message;
}

function ConfirmTwoFactorResFromObject(obj: ConfirmTwoFactorRes.AsObject | undefined): ConfirmTwoFactorRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ConfirmTwoFactorRes();
	(obj.recoveryCodes || [])
		.forEach((item) => message.addRecoveryCodes(item));
	return message;
}

function DisableTwoFactorReqFromObject(obj: DisableTwoFactorReq.AsObject | undefined): DisableTwoFactorReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DisableTwoFactorReq();
	message.setPassword(obj.password);
	return message;
}

function ResetTwoFactorReqFromObject(obj: ResetTwoFactorReq.AsObject | undefined): ResetTwoFactorReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ResetTwoFactorReq();
	message.setName(obj.name);
	return message;
}

function RevokeAccessReqFromObject(obj: RevokeAccessReq.AsObject | undefined): RevokeAccessReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new RevokeAccessReq();
	message.setName(obj.name);
	return message;
}

function RevokeAccessResFromObject(obj: RevokeAccessRes.AsObject | undefined): RevokeAccessRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new RevokeAccessRes();
	message.setDevicesBlocked(obj.devicesBlocked);
	message.setTokensDeleted(obj.tokensDeleted);
	message.setSessionsEnded(obj.sessionsEnded);
	return message;
}

function EmptyFromObject(obj: googleProtobufEmpty.Empty.AsObject | undefined): googleProtobufEmpty.Empty | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufEmpty.Empty();
	return message;
}

