// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: users.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// unset: the server has not seen them sign in
	LastLogin *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	// the access policies their identity provider put them in at that login.
	// Empty: their devices may reach what vpn.allowedIPs says.
	Policies []string `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	// whether they are asked for a second factor when they sign in
	TwoFactor     bool `protobuf:"varint,5,opt,name=two_factor,json=twoFactor,proto3" json:"two_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *User) GetTwoFactor() bool {
	if x != nil {
		return x.TwoFactor
	}
	return false
}

type ListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReq) Reset() {
	*x = ListUsersReq{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReq) ProtoMessage() {}

func (x *ListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReq.ProtoReflect.Descriptor instead.
func (*ListUsersReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

type ListUsersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*User                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRes) Reset() {
	*x = ListUsersRes{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRes) ProtoMessage() {}

func (x *ListUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRes.ProtoReflect.Descriptor instead.
func (*ListUsersRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRes) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangePasswordReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePasswordReq) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// Changing the password signs the other browsers out: whoever knew the old one
// must not keep a session that was made with it.
type ChangePasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionsEnded int32                  `protobuf:"varint,1,opt,name=sessions_ended,json=sessionsEnded,proto3" json:"sessions_ended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRes) Reset() {
	*x = ChangePasswordRes{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRes) ProtoMessage() {}

func (x *ChangePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRes.ProtoReflect.Descriptor instead.
func (*ChangePasswordRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordRes) GetSessionsEnded() int32 {
	if x != nil {
		return x.SessionsEnded
	}
	return 0
}

type StartTwoFactorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTwoFactorReq) Reset() {
	*x = StartTwoFactorReq{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTwoFactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTwoFactorReq) ProtoMessage() {}

func (x *StartTwoFactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTwoFactorReq.ProtoReflect.Descriptor instead.
func (*StartTwoFactorReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

type StartTwoFactorRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the shared secret, for whoever cannot scan a QR code
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// the otpauth:// URI the QR code holds
	Uri           string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTwoFactorRes) Reset() {
	*x = StartTwoFactorRes{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTwoFactorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTwoFactorRes) ProtoMessage() {}

func (x *StartTwoFactorRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTwoFactorRes.ProtoReflect.Descriptor instead.
func (*StartTwoFactorRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *StartTwoFactorRes) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *StartTwoFactorRes) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ConfirmTwoFactorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTwoFactorReq) Reset() {
	*x = ConfirmTwoFactorReq{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTwoFactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTwoFactorReq) ProtoMessage() {}

func (x *ConfirmTwoFactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTwoFactorReq.ProtoReflect.Descriptor instead.
func (*ConfirmTwoFactorReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmTwoFactorReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// The recovery codes, shown once. What the server keeps cannot produce them
// again.
type ConfirmTwoFactorRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryCodes []string               `protobuf:"bytes,1,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTwoFactorRes) Reset() {
	*x = ConfirmTwoFactorRes{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTwoFactorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTwoFactorRes) ProtoMessage() {}

func (x *ConfirmTwoFactorRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTwoFactorRes.ProtoReflect.Descriptor instead.
func (*ConfirmTwoFactorRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmTwoFactorRes) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

type DisableTwoFactorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableTwoFactorReq) Reset() {
	*x = DisableTwoFactorReq{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableTwoFactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTwoFactorReq) ProtoMessage() {}

func (x *DisableTwoFactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTwoFactorReq.ProtoReflect.Descriptor instead.
func (*DisableTwoFactorReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *DisableTwoFactorReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetTwoFactorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTwoFactorReq) Reset() {
	*x = ResetTwoFactorReq{}
	mi := &file_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTwoFactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTwoFactorReq) ProtoMessage() {}

func (x *ResetTwoFactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTwoFactorReq.ProtoReflect.Descriptor instead.
func (*ResetTwoFactorReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{11}
}

func (x *ResetTwoFactorReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RevokeAccessReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessReq) Reset() {
	*x = RevokeAccessReq{}
	mi := &file_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessReq) ProtoMessage() {}

func (x *RevokeAccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessReq.ProtoReflect.Descriptor instead.
func (*RevokeAccessReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeAccessReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// What the revocation took away. A user who was already blocked everywhere
// gives three zeros - it is not an error to revoke twice.
type RevokeAccessRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DevicesBlocked int32                  `protobuf:"varint,1,opt,name=devices_blocked,json=devicesBlocked,proto3" json:"devices_blocked,omitempty"`
	TokensDeleted  int32                  `protobuf:"varint,2,opt,name=tokens_deleted,json=tokensDeleted,proto3" json:"tokens_deleted,omitempty"`
	SessionsEnded  int32                  `protobuf:"varint,3,opt,name=sessions_ended,json=sessionsEnded,proto3" json:"sessions_ended,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeAccessRes) Reset() {
	*x = RevokeAccessRes{}
	mi := &file_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessRes) ProtoMessage() {}

func (x *RevokeAccessRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessRes.ProtoReflect.Descriptor instead.
func (*RevokeAccessRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeAccessRes) GetDevicesBlocked() int32 {
	if x != nil {
		return x.DevicesBlocked
	}
	return 0
}

func (x *RevokeAccessRes) GetTokensDeleted() int32 {
	if x != nil {
		return x.TokensDeleted
	}
	return 0
}

func (x *RevokeAccessRes) GetSessionsEnded() int32 {
	if x != nil {
		return x.SessionsEnded
	}
	return 0
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x129\n" +
	"\n" +
	"last_login\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x1a\n" +
	"\bpolicies\x18\x04 \x03(\tR\bpolicies\x12\x1d\n" +
	"\n" +
	"two_factor\x18\x05 \x01(\bR\ttwoFactor\"\x0e\n" +
	"\fListUsersReq\"1\n" +
	"\fListUsersRes\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.proto.UserR\x05items\"#\n" +
	"\rDeleteUserReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"a\n" +
	"\x11ChangePasswordReq\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\":\n" +
	"\x11ChangePasswordRes\x12%\n" +
	"\x0esessions_ended\x18\x01 \x01(\x05R\rsessionsEnded\"\x13\n" +
	"\x11StartTwoFactorReq\"=\n" +
	"\x11StartTwoFactorRes\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\")\n" +
	"\x13ConfirmTwoFactorReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"<\n" +
	"\x13ConfirmTwoFactorRes\x12%\n" +
	"\x0erecovery_codes\x18\x01 \x03(\tR\rrecoveryCodes\"1\n" +
	"\x13DisableTwoFactorReq\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"'\n" +
	"\x11ResetTwoFactorReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\x0fRevokeAccessReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x88\x01\n" +
	"\x0fRevokeAccessRes\x12'\n" +
	"\x0fdevices_blocked\x18\x01 \x01(\x05R\x0edevicesBlocked\x12%\n" +
	"\x0etokens_deleted\x18\x02 \x01(\x05R\rtokensDeleted\x12%\n" +
	"\x0esessions_ended\x18\x03 \x01(\x05R\rsessionsEnded2\xae\x04\n" +
	"\x05Users\x127\n" +
	"\tListUsers\x12\x13.proto.ListUsersReq\x1a\x13.proto.ListUsersRes\"\x00\x12<\n" +
	"\n" +
	"DeleteUser\x12\x14.proto.DeleteUserReq\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\fRevokeAccess\x12\x16.proto.RevokeAccessReq\x1a\x16.proto.RevokeAccessRes\"\x00\x12F\n" +
	"\x0eChangePassword\x12\x18.proto.ChangePasswordReq\x1a\x18.proto.ChangePasswordRes\"\x00\x12F\n" +
	"\x0eStartTwoFactor\x12\x18.proto.StartTwoFactorReq\x1a\x18.proto.StartTwoFactorRes\"\x00\x12L\n" +
	"\x10ConfirmTwoFactor\x12\x1a.proto.ConfirmTwoFactorReq\x1a\x1a.proto.ConfirmTwoFactorRes\"\x00\x12H\n" +
	"\x10DisableTwoFactor\x12\x1a.proto.DisableTwoFactorReq\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x0eResetTwoFactor\x12\x18.proto.ResetTwoFactorReq\x1a\x16.google.protobuf.Empty\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_users_proto_goTypes = []any{
	(*User)(nil),                  // 0: proto.User
	(*ListUsersReq)(nil),          // 1: proto.ListUsersReq
	(*ListUsersRes)(nil),          // 2: proto.ListUsersRes
	(*DeleteUserReq)(nil),         // 3: proto.DeleteUserReq
	(*ChangePasswordReq)(nil),     // 4: proto.ChangePasswordReq
	(*ChangePasswordRes)(nil),     // 5: proto.ChangePasswordRes
	(*StartTwoFactorReq)(nil),     // 6: proto.StartTwoFactorReq
	(*StartTwoFactorRes)(nil),     // 7: proto.StartTwoFactorRes
	(*ConfirmTwoFactorReq)(nil),   // 8: proto.ConfirmTwoFactorReq
	(*ConfirmTwoFactorRes)(nil),   // 9: proto.ConfirmTwoFactorRes
	(*DisableTwoFactorReq)(nil),   // 10: proto.DisableTwoFactorReq
	(*ResetTwoFactorReq)(nil),     // 11: proto.ResetTwoFactorReq
	(*RevokeAccessReq)(nil),       // 12: proto.RevokeAccessReq
	(*RevokeAccessRes)(nil),       // 13: proto.RevokeAccessRes
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_users_proto_depIdxs = []int32{
	14, // 0: proto.User.last_login:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.ListUsersRes.items:type_name -> proto.User
	1,  // 2: proto.Users.ListUsers:input_type -> proto.ListUsersReq
	3,  // 3: proto.Users.DeleteUser:input_type -> proto.DeleteUserReq
	12, // 4: proto.Users.RevokeAccess:input_type -> proto.RevokeAccessReq
	4,  // 5: proto.Users.ChangePassword:input_type -> proto.ChangePasswordReq
	6,  // 6: proto.Users.StartTwoFactor:input_type -> proto.StartTwoFactorReq
	8,  // 7: proto.Users.ConfirmTwoFactor:input_type -> proto.ConfirmTwoFactorReq
	10, // 8: proto.Users.DisableTwoFactor:input_type -> proto.DisableTwoFactorReq
	11, // 9: proto.Users.ResetTwoFactor:input_type -> proto.ResetTwoFactorReq
	2,  // 10: proto.Users.ListUsers:output_type -> proto.ListUsersRes
	15, // 11: proto.Users.DeleteUser:output_type -> google.protobuf.Empty
	13, // 12: proto.Users.RevokeAccess:output_type -> proto.RevokeAccessRes
	5,  // 13: proto.Users.ChangePassword:output_type -> proto.ChangePasswordRes
	7,  // 14: proto.Users.StartTwoFactor:output_type -> proto.StartTwoFactorRes
	9,  // 15: proto.Users.ConfirmTwoFactor:output_type -> proto.ConfirmTwoFactorRes
	15, // 16: proto.Users.DisableTwoFactor:output_type -> google.protobuf.Empty
	15, // 17: proto.Users.ResetTwoFactor:output_type -> google.protobuf.Empty
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
